packer {
  required_plugins {
    amazon = {
      version = ">= 0.0.2"
      source  = "github.com/hashicorp/amazon"
    }
  }
}

variable "AWS_ACCESS_KEY_ID" {
  type    = string
  default = ""
}

variable "aws_region" {
  type    = string
  default = "us-east-1"
}

variable "AWS_SECRET_ACCESS_KEY" {
  type    = string
  default = ""
}

variable "source_ami" {
  type    = string
  default = "ami-033b95fb8079dc481"
}

variable "ssh_username" {
  type    = string
  default = "ec2-user"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  access_key    = "${var.AWS_ACCESS_KEY_ID}"
  secret_key    = "${var.AWS_SECRET_ACCESS_KEY}"
  ami_description = "Amazon Linux AMI for CSYE 6225"
  ami_name        = "csye6225_spring2022_${local.timestamp}"
  instance_type   = "t2.micro"
  region       = "${var.aws_region}"
  source_ami   = "${var.source_ami}"
  ssh_username = "${var.ssh_username}"
  ami_users     = ["282741675015"]
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "file" 
    source = "webservice.zip"
    destination = "~/"
  

  provisioner "shell" {
      inline =  [
      "cd ~",
      "sudo mkdir -p webservice",
      "sudo chmod 755 webservice",
      "sudo unzip webservice.zip -d ~/webservice",
      "ls -a"
      ]
  }

  provisioner "shell" {
    scripts = [
      "script.sh"
    ]
  }
}
