version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/webservice
    overwrite: true
file_exists_behavior: OVERWRITE

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 180
      runas: ec2-user