---
name: Packer Build

on:
  push:
    branches: [ main ]

jobs:
  packer:
    name: run checks
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '16'
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install Node Packages
      run: npm ci

    - name: Zip files
      run: zip -r webservice.zip .

    - name: Build Deployment Artifact
      run: | 
        mkdir codedeploy_artifact
        zip -r build_artifact .
        pwd
        mv build_artifact.zip codedeploy_artifact
        cd codedeploy_artifact

    - name: Packer Init
      uses: hashicorp/packer-github-actions@master
      with:
        command: init
        target: ami.pkr.hcl

    - name: Packer Validate
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        target: ami.pkr.hcl

    - name: Packer Build
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: -var=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -var=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        target: ami.pkr.hcl

    - name: Copy Artifacts to S3
      run: |
      aws s3 sync ./codedeploy_artifact s3://${{secrets.S3_BUCKET}}
      echo ${{secrets.S3_BUCKET}}
        

    - name: Creating AWS Deployment
      run: |
      output=$(aws deploy create-deployment \
          --application-name csye6225-webapp \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name csye6225-webapp-deployment \
          --description "CSYE6255 - CodeDeploy" \
          --s3-location bucket=${{secrets.S3_BUCKET}},key=build_artifact.zip,bundleType=zip \
          --region ${{secrets.AWS_REGION}} \
          --output json)
          depId=$(echo $output | jq -r '.deploymentId')
          aws deploy wait deployment-successful --deployment-id $depId
          
      env:
          AWS_S3_BUCKET: ${{secrets.S3_BUCKET}}