---
name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  packer:
    name: run checks
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '16'
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install Node Packages
      run: npm ci

    - name: Zip files
      run: zip -r webservice.zip .

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Build Deployment Artifact
      run: | 
        mkdir codedeploy_artifact
        zip -r build_artifact .
        pwd
        mv build_artifact.zip codedeploy_artifact
        cd codedeploy_artifact

    - name: Packer Init
      uses: hashicorp/packer-github-actions@master
      with:
        command: init
        target: ami.pkr.hcl

    - name: Packer Validate
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        target: ami.pkr.hcl

    - name: Packer Build
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: -var=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -var=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} -var=AWS_REGION=${{ secrets.AWS_REGION }}
        target: ami.pkr.hcl
        
    - name: Upload Zip to S3
        run: |
          aws deploy push \
          --application-name csye6225-webapp \
          --description "Latest revision for csye6225-webapp-${{ github.sha }}" \
          --ignore-hidden-files \
          --s3-location s3://${{ secrets.S3_BUCKET }}/csye6225-webapp-${{ github.sha}}.zip \
          --source .

    - name: Creating AWS Deployment
      run: |
        aws deploy create-deployment \
           --application-name csye6225-webapp \
           --deployment-config-name CodeDeployDefault.AllAtOnce \
           --deployment-group-name csye6225-webapp-deployment \
           --file-exists-behavior OVERWRITE \
           --s3-location bucket=${{ secrets.S3_BUCKET }},key=csye6225-webapp-${{ github.sha }}.zip,bundleType=zip \
          
      env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET: ${{secrets.S3_BUCKET}}