---
name: Packer Build on Pull Requests

on:
  pull_request:
    branches:
    - main
  push:
    branches: [ main ]

jobs:
  packer:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js '16'
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: Install Node Packages
      run: npm ci
    - run: npm run build --if-present
    - name: Running Unit Test
      run: npm test
    - name: Zip files
      run: zip -r webservice.zip .
    - name: Packer Init
      uses: hashicorp/packer-github-actions@master
      with:
        command: init
        target: ami.pkr.hcl
    - name: Packer Validate
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        target: ami.pkr.hcl
    - name: Packer Build
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: -var=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} -var=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        target: ami.pkr.hcl